version: v2beta1
name: level1-plc

dev:
  plc-dev:
    # 1. Busca el Pod que desplegó ArgoCD usando etiquetas
    labelSelector:
      app: plc-virtual
    
    # 2. 🔑 AQUÍ SE HACE EL ENLACE DE CARPETAS
    sync:
    - path: ./level1-plc/:/app  # <--- [Ruta_Local]:[Ruta_Contenedor]
      excludePaths:
      - .git/
    
    # 3. Qué comando ejecutar automáticamente dentro del contenedor
    terminal:
      command: cd /app && pip install asyncua && python server.py
    
    # 4. Redirección de puertos para probarlo desde Windows
    ports:
    - portMapping: "4840:4840"